// src/app/chatbot/chat-header/chat-header.component.ts

import { Component, EventEmitter, Input, Output } from '@angular/core';
import { trigger, transition, style, animate } from '@angular/animations';

@Component({
  selector: 'app-chat-header',
  templateUrl: './chat-header.component.html',
  styleUrls: ['./chat-header.component.scss'],
  animations: [
    trigger('fadeIn', [
      transition(':enter', [
        style({ opacity: 0 }),
        animate('0.3s ease-out', style({ opacity: 1 }))
      ])
    ])
  ]
})
export class ChatHeaderComponent {
  @Input() title = 'Chat';
  @Input() isMaximized = false;
  @Input() showHistoryButton = true;
  
  @Output() toggleHistory = new EventEmitter<void>();
  @Output() toggleMaximize = new EventEmitter<void>();
  @Output() close = new EventEmitter<void>();
}


<div [@fadeIn] class="flex items-center justify-between p-4 border-b border-gray-100">
  <div class="flex items-center gap-2">
    <button
      *ngIf="showHistoryButton"
      (click)="toggleHistory.emit()"
      class="p-1 rounded-full hover:bg-gray-100 transition-colors"
      aria-label="Toggle chat history">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="3" y1="12" x2="21" y2="12"></line>
        <line x1="3" y1="6" x2="21" y2="6"></line>
        <line x1="3" y1="18" x2="21" y2="18"></line>
      </svg>
    </button>
    <h2 class="font-medium">{{title}}</h2>
  </div>
  
  <div class="flex items-center">
    <button
      (click)="toggleMaximize.emit()"
      class="p-1 rounded-full hover:bg-gray-100 transition-colors mr-1"
      aria-label="Maximize or minimize chatbot">
      <svg *ngIf="isMaximized" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="4 14 10 14 10 20"></polyline>
        <polyline points="20 10 14 10 14 4"></polyline>
        <line x1="14" y1="10" x2="21" y2="3"></line>
        <line x1="3" y1="21" x2="10" y2="14"></line>
      </svg>
      <svg *ngIf="!isMaximized" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="15 3 21 3 21 9"></polyline>
        <polyline points="9 21 3 21 3 15"></polyline>
        <line x1="21" y1="3" x2="14" y2="10"></line>
        <line x1="3" y1="21" x2="10" y2="14"></line>
      </svg>
    </button>
    
    <button
      (click)="close.emit()"
      class="p-1 rounded-full hover:bg-gray-100 transition-colors"
      aria-label="Close chatbot">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>
  </div>
</div>

// src/components/Chatbot/ChatHeader.tsx

import React from 'react';
import { motion } from 'framer-motion';
import { Menu, X, Maximize2, Minimize2 } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ChatHeaderProps {
  title: string;
  onToggleHistory: () => void;
  onClose: () => void;
  onToggleMaximize: () => void;
  isMaximized: boolean;
  showHistoryButton?: boolean;
}

const ChatHeader: React.FC<ChatHeaderProps> = ({
  title,
  onToggleHistory,
  onClose,
  onToggleMaximize,
  isMaximized,
  showHistoryButton = true
}) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="flex items-center justify-between p-4 border-b border-gray-100"
    >
      <div className="flex items-center gap-2">
        {showHistoryButton && (
          <button
            onClick={onToggleHistory}
            className="p-1 rounded-full hover:bg-chatbot-secondary transition-colors"
            aria-label="Toggle chat history"
          >
            <Menu size={18} />
          </button>
        )}
        <h2 className="font-medium">{title}</h2>
      </div>
      
      <div className="flex items-center">
        <button
          onClick={onToggleMaximize}
          className="p-1 rounded-full hover:bg-chatbot-secondary transition-colors mr-1"
          aria-label={isMaximized ? "Minimize chatbot" : "Maximize chatbot"}
        >
          {isMaximized ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
        </button>
        
        <button
          onClick={onClose}
          className="p-1 rounded-full hover:bg-chatbot-secondary transition-colors"
          aria-label="Close chatbot"
        >
          <X size={18} />
        </button>
      </div>
    </motion.div>
  );
};

export default ChatHeader;
