// src/app/chatbot/chat-input/chat-input.component.ts

import { Component, ElementRef, EventEmitter, OnInit, Output, ViewChild } from '@angular/core';
import { trigger, transition, style, animate } from '@angular/animations';

@Component({
  selector: 'app-chat-input',
  templateUrl: './chat-input.component.html',
  styleUrls: ['./chat-input.component.scss'],
  animations: [
    trigger('optionsAnimation', [
      transition(':enter', [
        style({ opacity: 0, y: 10, scale: 0.95 }),
        animate('0.2s ease-out', style({ opacity: 1, y: 0, scale: 1 }))
      ]),
      transition(':leave', [
        animate('0.2s ease-in', style({ opacity: 0, y: 10, scale: 0.95 }))
      ])
    ]),
    trigger('optionAnimation', [
      transition(':enter', [
        style({ opacity: 0, x: -10 }),
        animate('0.2s ease-out', style({ opacity: 1, x: 0 }))
      ])
    ])
  ]
})
export class ChatInputComponent implements OnInit {
  @Output() sendMessage = new EventEmitter<string>();
  @Output() uploadImage = new EventEmitter<File>();
  @Output() uploadDocument = new EventEmitter<File>();

  @ViewChild('imageInput') imageInput: ElementRef;
  @ViewChild('documentInput') documentInput: ElementRef;

  message = '';
  showOptions = false;

  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {
    // Listen for clicks outside the options menu to close it
    document.addEventListener('mousedown', this.onClickOutside.bind(this));
  }

  ngOnDestroy(): void {
    document.removeEventListener('mousedown', this.onClickOutside.bind(this));
  }

  onClickOutside(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const optionsContainer = this.elementRef.nativeElement.querySelector('#chatbot-options');
    const plusButton = this.elementRef.nativeElement.querySelector('#plus-button');
    
    if (this.showOptions && 
        optionsContainer && 
        !optionsContainer.contains(target) && 
        plusButton && 
        !plusButton.contains(target)) {
      this.showOptions = false;
    }
  }

  toggleOptions(): void {
    this.showOptions = !this.showOptions;
  }

  handleSubmit(): void {
    if (this.message.trim()) {
      this.sendMessage.emit(this.message);
      this.message = '';
    }
  }

  triggerImageUpload(): void {
    this.imageInput.nativeElement.click();
    this.showOptions = false;
  }

  triggerDocumentUpload(): void {
    this.documentInput.nativeElement.click();
    this.showOptions = false;
  }

  handleImageUpload(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.uploadImage.emit(input.files[0]);
      input.value = '';
    }
  }

  handleDocumentUpload(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.uploadDocument.emit(input.files[0]);
      input.value = '';
    }
  }
}


<div class="relative p-4 border-t border-gray-100">
  <form (ngSubmit)="handleSubmit()" class="flex items-center gap-2">
    <div class="relative">
      <button
        type="button"
        id="plus-button"
        (click)="toggleOptions()"
        class="h-10 w-10 rounded-full flex items-center justify-center bg-gray-100 hover:bg-gray-200 transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-blue-600">
          <circle cx="12" cy="12" r="10"></circle>
          <line x1="12" y1="8" x2="12" y2="16"></line>
          <line x1="8" y1="12" x2="16" y2="12"></line>
        </svg>
      </button>
      
      <div 
        *ngIf="showOptions" 
        [@optionsAnimation]
        id="chatbot-options"
        class="absolute bottom-14 left-0 bg-white rounded-lg shadow-lg py-2 w-36 z-10">
        <button
          *ngFor="let option of [
            { icon: 'image', label: 'Image', action: 'triggerImageUpload' },
            { icon: 'file-text', label: 'Document', action: 'triggerDocumentUpload' }
          ]; let i = index"
          type="button"
          [@optionAnimation]="{ value: '', params: { delay: i * 0.05 } }"
          (click)="this[option.action]()"
          class="flex items-center gap-2 w-full px-3 py-2 hover:bg-gray-100 text-left text-sm"
        >
          <span class="text-blue-600">
            <svg *ngIf="option.icon === 'image'" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
              <circle cx="8.5" cy="8.5" r="1.5"></circle>
              <polyline points="21 15 16 10 5 21"></polyline>
            </svg>
            <svg *ngIf="option.icon === 'file-text'" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
              <polyline points="14 2 14 8 20 8"></polyline>
              <line x1="16" y1="13" x2="8" y2="13"></line>
              <line x1="16" y1="17" x2="8" y2="17"></line>
              <polyline points="10 9 9 9 8 9"></polyline>
            </svg>
          </span>
          <span>{{option.label}}</span>
        </button>
      </div>
      
      <input
        type="file"
        #imageInput
        class="hidden"
        accept="image/*"
        (change)="handleImageUpload($event)"
      />
      
      <input
        type="file"
        #documentInput
        class="hidden"
        accept=".pdf,.doc,.docx,.txt"
        (change)="handleDocumentUpload($event)"
      />
    </div>
    
    <input
      type="text"
      [(ngModel)]="message"
      name="message"
      placeholder="Type a message..."
      class="flex-1 py-2 px-4 bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-400/30 transition-all"
    />
    
    <button
      type="submit"
      [disabled]="!message.trim()"
      [ngClass]="message.trim() 
        ? 'bg-blue-600 text-white' 
        : 'bg-gray-200 text-gray-400 cursor-not-allowed'"
      class="h-10 w-10 rounded-full flex items-center justify-center transition-all duration-200"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="22" y1="2" x2="11" y2="13"></line>
        <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
      </svg>
    </button>
  </form>
</div>

// src/components/Chatbot/ChatInput.tsx

import React, { useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { Send, PlusCircle, Image, FileText } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ChatInputProps {
  onSendMessage: (message: string) => void;
  onUploadImage: (file: File) => void;
  onUploadDocument: (file: File) => void;
}

const ChatInput: React.FC<ChatInputProps> = ({ 
  onSendMessage, 
  onUploadImage,
  onUploadDocument
}) => {
  const [message, setMessage] = useState('');
  const [showOptions, setShowOptions] = useState(false);
  const imageInputRef = useRef<HTMLInputElement>(null);
  const documentInputRef = useRef<HTMLInputElement>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (message.trim()) {
      onSendMessage(message);
      setMessage('');
    }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      onUploadImage(file);
      if (imageInputRef.current) {
        imageInputRef.current.value = '';
      }
    }
  };

  const handleDocumentUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      onUploadDocument(file);
      if (documentInputRef.current) {
        documentInputRef.current.value = '';
      }
    }
  };

  const toggleOptions = () => {
    setShowOptions(!showOptions);
  };

  return (
    <div className="relative p-4 border-t border-gray-100">
      <form onSubmit={handleSubmit} className="flex items-center gap-2">
        <div className="relative">
          <button
            type="button"
            onClick={toggleOptions}
            className="h-10 w-10 rounded-full flex items-center justify-center bg-chatbot-secondary hover:bg-gray-200 transition-colors"
          >
            <PlusCircle size={20} className="text-chatbot-accent" />
          </button>
          
          <AnimatedOptions 
            show={showOptions} 
            onClickOutside={() => setShowOptions(false)}
            onImageClick={() => imageInputRef.current?.click()}
            onDocumentClick={() => documentInputRef.current?.click()}
          />
          
          <input
            type="file"
            ref={imageInputRef}
            className="hidden"
            accept="image/*"
            onChange={handleImageUpload}
          />
          
          <input
            type="file"
            ref={documentInputRef}
            className="hidden"
            accept=".pdf,.doc,.docx,.txt"
            onChange={handleDocumentUpload}
          />
        </div>
        
        <input
          type="text"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          placeholder="Type a message..."
          className="flex-1 py-2 px-4 bg-chatbot-secondary rounded-full focus:outline-none focus:ring-2 focus:ring-chatbot-accent/30 transition-all"
        />
        
        <button
          type="submit"
          disabled={!message.trim()}
          className={cn(
            "h-10 w-10 rounded-full flex items-center justify-center transition-all",
            message.trim() 
              ? "bg-chatbot-accent text-white" 
              : "bg-gray-200 text-gray-400 cursor-not-allowed"
          )}
        >
          <Send size={18} />
        </button>
      </form>
    </div>
  );
};

interface AnimatedOptionsProps {
  show: boolean;
  onClickOutside: () => void;
  onImageClick: () => void;
  onDocumentClick: () => void;
}

const AnimatedOptions: React.FC<AnimatedOptionsProps> = ({ 
  show, 
  onClickOutside,
  onImageClick,
  onDocumentClick
}) => {
  const options = [
    { icon: <Image size={18} />, label: "Image", onClick: onImageClick },
    { icon: <FileText size={18} />, label: "Document", onClick: onDocumentClick }
  ];

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      const target = e.target as Node;
      const optionsContainer = document.getElementById('chatbot-options');
      const plusButton = document.getElementById('plus-button');
      
      if (
        optionsContainer && 
        !optionsContainer.contains(target) && 
        plusButton && 
        !plusButton.contains(target)
      ) {
        onClickOutside();
      }
    };

    if (show) {
      document.addEventListener('mousedown', handleClickOutside);
    }
    
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [show, onClickOutside]);

  if (!show) return null;

  return (
    <motion.div
      id="chatbot-options"
      initial={{ opacity: 0, y: 10, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: 10, scale: 0.95 }}
      transition={{ duration: 0.2 }}
      className="absolute bottom-14 left-0 bg-white rounded-lg shadow-lg py-2 w-36 z-10 chatbot-glass"
    >
      {options.map((option, index) => (
        <motion.button
          key={index}
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: index * 0.05 }}
          onClick={option.onClick}
          className="flex items-center gap-2 w-full px-3 py-2 hover:bg-chatbot-secondary text-left text-sm"
        >
          <span className="text-chatbot-accent">{option.icon}</span>
          <span>{option.label}</span>
        </motion.button>
      ))}
    </motion.div>
  );
};

export default ChatInput;
