// src/app/chatbot/chat-message/chat-message.component.ts

import { Component, Input } from '@angular/core';
import { trigger, transition, style, animate } from '@angular/animations';
import { MessageType } from '../models/chat.model';

@Component({
  selector: 'app-chat-message',
  templateUrl: './chat-message.component.html',
  styleUrls: ['./chat-message.component.scss'],
  animations: [
    trigger('messageAnimation', [
      transition(':enter', [
        style({ opacity: 0, y: 20 }),
        animate('0.3s ease-out', style({ opacity: 1, y: 0 }))
      ]),
      transition(':leave', [
        animate('0.3s ease-in', style({ opacity: 0 }))
      ])
    ])
  ]
})
export class ChatMessageComponent {
  @Input() message = '';
  @Input() type: MessageType = 'user';
  @Input() timestamp: Date = new Date();
  @Input() isLast = false;
}


<div
  [@messageAnimation]
  class="flex w-full max-w-full mb-4"
  [ngClass]="type === 'user' ? 'justify-end' : 'justify-start'"
>
  <div class="flex gap-3 max-w-[80%]" [ngClass]="type === 'user' ? 'flex-row-reverse' : 'flex-row'">
    <div 
      class="flex-shrink-0 flex items-start justify-center h-8 w-8 rounded-full"
      [ngClass]="type === 'user' ? 'bg-blue-600 text-white' : 'bg-gray-100 text-blue-600'"
    >
      <svg *ngIf="type === 'user'" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mt-[6px]">
        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
        <circle cx="12" cy="7" r="4"></circle>
      </svg>
      <svg *ngIf="type === 'bot'" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mt-[6px]">
        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
        <path d="M11 5h2a2 2 0 0 1 2 2v4h-6V7a2 2 0 0 1 2-2z"></path>
      </svg>
    </div>
    
    <div class="flex flex-col">
      <div 
        class="px-4 py-3 rounded-xl break-words"
        [ngClass]="type === 'user' 
          ? 'bg-blue-600 text-white rounded-tr-none' 
          : 'bg-gray-100 text-gray-900 rounded-tl-none'"
      >
        <p class="text-sm">{{message}}</p>
      </div>
      <span 
        class="text-xs mt-1 text-gray-500"
        [ngClass]="type === 'user' ? 'text-right mr-1' : 'text-left ml-1'"
      >
        {{timestamp | date:'shortTime'}}
      </span>
    </div>
  </div>
</div>

// src/components/Chatbot/ChatMessage.tsx

import React from 'react';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';
import { User, Bot } from 'lucide-react';

export type MessageType = 'user' | 'bot';

interface ChatMessageProps {
  message: string;
  type: MessageType;
  timestamp: Date;
  isLast?: boolean;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ 
  message, 
  type, 
  timestamp,
  isLast = false
}) => {
  const isUser = type === 'user';
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className={cn(
        "flex w-full max-w-full mb-4 chatbot-message-transition",
        isUser ? "justify-end" : "justify-start"
      )}
    >
      <div className={cn(
        "flex gap-3 max-w-[80%]",
        isUser ? "flex-row-reverse" : "flex-row"
      )}>
        <div className={cn(
          "flex-shrink-0 flex items-start justify-center h-8 w-8 rounded-full",
          isUser ? "bg-chatbot-accent text-white" : "bg-chatbot-secondary text-chatbot-accent"
        )}>
          {isUser ? (
            <User size={16} className="mt-[6px]" />
          ) : (
            <Bot size={16} className="mt-[6px]" />
          )}
        </div>
        
        <div className="flex flex-col">
          <div className={cn(
            "px-4 py-3 rounded-xl break-words",
            isUser 
              ? "bg-chatbot-accent text-white rounded-tr-none" 
              : "bg-chatbot-secondary text-foreground rounded-tl-none"
          )}>
            <p className="text-sm">{message}</p>
          </div>
          <span className={cn(
            "text-xs mt-1 text-chatbot-muted",
            isUser ? "text-right mr-1" : "text-left ml-1"
          )}>
            {timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </div>
      </div>
    </motion.div>
  );
};

export default ChatMessage;
